In [8]:
import pandas as pd

In [26]:
data = pd.read_csv('Algerian_forest_fires_dataset_UPDATE.csv', sep='\\s*,\\s*', skipinitialspace=True, skiprows=[0,124,125,126], engine='python')

In [27]:
data.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0,not fire
4,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire

In [40]:
data['Classes'] = data['Classes'].replace(['not fire', 'fire'], [0, 1])

numerical_columns = ["Temperature", "RH", "Ws", "Rain", "FFMC", "DMC", "DC", "ISI", "BUI", "FWI"]
for column in numerical_columns:
    data[column] = pd.to_numeric(data[column], errors='coerce')


input_variables = ["Temperature", "RH", "Ws", "Rain"]
fwi_variables = ["FFMC", "DMC", "DC", "ISI", "BUI"]
fwi = ["FWI"]

data = data.dropna(subset=input_variables + fwi_variables + fwi + ['Classes'])

In [41]:
from sklearn.model_selection import train_test_split

X1 = data[input_variables]
X2 = data[fwi_variables]
X3 = data[fwi]
X4 = data[input_variables + fwi_variables + fwi]

Y = data['Classes']

X1_train, X1_test, Y_train, Y_test = train_test_split(X1, Y, test_size=0.2, random_state = 42)
X2_train, X2_test, Y_train, Y_test = train_test_split(X2, Y, test_size=0.2, random_state = 42)
X3_train, X3_test, Y_train, Y_test = train_test_split(X3, Y, test_size=0.2, random_state = 42)
X4_train, X4_test, Y_train, Y_test = train_test_split(X4, Y, test_size=0.2, random_state = 42)

In [62]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

clf = DecisionTreeClassifier()
clf2 = clf.fit(X2_train, Y_train)

In [63]:
Y2_pred = clf2.predict(X2_test)

accuracy2 = accuracy_score(Y_test, Y2_pred)
print(f"Accuracy: {accuracy2:.2f}")

print(classification_report(Y_test, Y2_pred))

# Print the confusion matrix
print(confusion_matrix(Y_test, Y2_pred))

Accuracy: 0.98
              precision    recall  f1-score   support

         0.0       0.96      1.00      0.98        22
         1.0       1.00      0.96      0.98        27

    accuracy                           0.98        49
   macro avg       0.98      0.98      0.98        49
weighted avg       0.98      0.98      0.98        49

[[22  0]
 [ 1 26]]